# Generated by Django 4.2.11 on 2024-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('pub_date', models.DateField(verbose_name='Published Date')),
            ],
        ),
    ]
